# Generated by Django 5.1.7 on 2025-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Movie_name', models.CharField(max_length=50)),
                ('Ratings', models.FloatField(primary_key='Ratings', serialize=False)),
                ('Cast', models.CharField(max_length=50)),
                ('Release_year', models.DateField()),
                ('Genre', models.CharField(max_length=50)),
            ],
        ),
    ]
